### PR TITLE
Rename RubyVM::DebugInspector to DebugInspector and add support for truffleruby

### PR DESCRIPTION
**Pull request by eregon**
* Fixes https://github.com/banister/debug_inspector/issues/36
* Also update CI.

### CODE REVIEW

**Comment by eregon** [comment]
This is now green and ready for review. cc @RobinDaugherty

**Comment by eregon** [comment]
Ping, I'd love a review of this.

**Comment by eregon** [comment]
@RobinDaugherty Ping :)

**Comment by eregon** [comment]
Ping

**Comment by banister** [comment]
@eregon i gave you write access to this repo

**Comment by banister** [comment]
Hi @eregon i added you as a gem owner, let me know if you got the link. It's a very shit UI, i'm actually shocked how terrible the rubygems UI is. Anyway, hopefully you got it.

**Comment by eregon** [comment]
@banister I haven't received the email (yet?) unfortunately.
Do you see me in the list at https://rubygems.org/gems/debug_inspector/owners ?
If you need it, my email is eregontp (gmail).

**Comment by banister** [comment]
the email worked, LMK how it goes

**Comment by eregon** [comment]
Thanks! That worked.

**Pull request merged**
